### ISSUE TITLE
Unable to start app by instruction: "ReferenceError: Response is not defined"

### ISSUE THREAD

**Issue by snowindy** [Ironclad/rivet-example#10]
When running app by instruction I get the following output: "ReferenceError: Response is not defined"

What should I do?
// npm and node versions are in the output

```
$ node -v
v16.14.2

$ npm -v
8.19.2


$ npm start

> rivet-example@0.1.0 start
> concurrently --kill-others "cd server && npm run dev" "cd app && npm run start"

[0]
[0] > express-gen-ts@0.0.0 dev
[0] > nodemon
[0]
[1]
[1] > app@0.1.0 start
[1] > react-scripts start
[1]
[0] [nodemon] 3.0.1
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): src\**\*
[0] [nodemon] watching extensions: ts,html
[0] [nodemon] starting `./node_modules/.bin/ts-node --files -r tsconfig-paths/register ./src`
[0] C:\propz\rivet-example\server\node_modules\@ironclad\rivet-core\dist\cjs\bundle.cjs:1652
[0] var EventSourceResponse = class extends Response {
[0]                           ^
[0] ReferenceError: Response is not defined
[0]     at Object.<anonymous> (C:\propz\rivet-example\server\node_modules\@ironclad\rivet-core\dist\cjs\bundle.cjs:1652:27)
[0]     at Module._compile (node:internal/modules/cjs/loader:1103:14)
[0]     at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
[0]     at Object.require.extensions.<computed> [as .js] (C:\propz\rivet-example\server\node_modules\ts-node\src\index.ts:1608:43)
[0]     at Module.load (node:internal/modules/cjs/loader:981:32)
[0]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[0]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[0]     at require (node:internal/modules/cjs/helpers:102:18)
[0]     at Object.<anonymous> (C:\propz\rivet-example\server\node_modules\@ironclad\rivet-node\dist\cjs\bundle.cjs:48:25)
[0]     at Module._compile (node:internal/modules/cjs/loader:1103:14)
[0] [nodemon] app crashed - waiting for file changes before starting...
[1] (node:26136) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' opt
ion.
[1] (Use `node --trace-deprecation ...` to show where the warning was created)
[1] (node:26136) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' o
ption.
[1] Starting the development server...
[1]
[1] Compiled successfully!
[1]
[1] You can now view app in the browser.
[1]
[1]   Local:            http://localhost:3000
[1]   On Your Network:  http://192.168.1.11:3000
[1]
[1] Note that the development build is not optimized.
[1] To create a production build, use npm run build.
[1]
[1] webpack compiled successfully
```

**Comment by snowindy** [comment]
Updating to most recent node helped.
```
$ node -v
v20.10.0
```
